version: '3.8'

services:

  # gateway:
  #   container_name: gateway-service
  #   build:
  #     context: ./services
  #     dockerfile: Dockerfile.gateway
  #   ports:
  #     - "80:8080"
  #   env_file:
  #     - ./services/gateway/.env.prod
  #   depends_on:
  #     - managers_service

  managers_service:
    container_name: managers-service
    build:
      context: ./deploy
      dockerfile: Dockerfile.managers
    ports:
      - "8081:8081"
    depends_on:
      - managers_db
    env_file:
      - ./managers-svc/.env.prod

  managers_db:
    image: postgres:latest
    container_name: managers-postgres
    env_file:
      - ./managers-svc/.env.prod
    volumes:
      - ./migrations/managers-svc:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    command: "-DV"
    networks:
      - default

networks:
  default:
    driver: bridge