services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"

  nats:
    image: nats:2
    restart: always
    ports:
      - "4222:4222"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"