// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/interface.go
//
// Generated by this command:
//
//	mockgen -source=usecase/interface.go -destination=usecase/mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/mephirious/helper-for-teachers/services/exam-svc/internal/domain"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskUseCase is a mock of TaskUseCase interface.
type MockTaskUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTaskUseCaseMockRecorder
	isgomock struct{}
}

// MockTaskUseCaseMockRecorder is the mock recorder for MockTaskUseCase.
type MockTaskUseCaseMockRecorder struct {
	mock *MockTaskUseCase
}

// NewMockTaskUseCase creates a new mock instance.
func NewMockTaskUseCase(ctrl *gomock.Controller) *MockTaskUseCase {
	mock := &MockTaskUseCase{ctrl: ctrl}
	mock.recorder = &MockTaskUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskUseCase) EXPECT() *MockTaskUseCaseMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskUseCase) CreateTask(ctx context.Context, task *domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskUseCaseMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskUseCase)(nil).CreateTask), ctx, task)
}

// DeleteTask mocks base method.
func (m *MockTaskUseCase) DeleteTask(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskUseCaseMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskUseCase)(nil).DeleteTask), ctx, id)
}

// GetAllTasks mocks base method.
func (m *MockTaskUseCase) GetAllTasks(ctx context.Context) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", ctx)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockTaskUseCaseMockRecorder) GetAllTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockTaskUseCase)(nil).GetAllTasks), ctx)
}

// GetTaskByID mocks base method.
func (m *MockTaskUseCase) GetTaskByID(ctx context.Context, id primitive.ObjectID) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, id)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskUseCaseMockRecorder) GetTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskUseCase)(nil).GetTaskByID), ctx, id)
}

// GetTasksByExamID mocks base method.
func (m *MockTaskUseCase) GetTasksByExamID(ctx context.Context, examID primitive.ObjectID) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByExamID", ctx, examID)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByExamID indicates an expected call of GetTasksByExamID.
func (mr *MockTaskUseCaseMockRecorder) GetTasksByExamID(ctx, examID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByExamID", reflect.TypeOf((*MockTaskUseCase)(nil).GetTasksByExamID), ctx, examID)
}

// UpdateTask mocks base method.
func (m *MockTaskUseCase) UpdateTask(ctx context.Context, task *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskUseCaseMockRecorder) UpdateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskUseCase)(nil).UpdateTask), ctx, task)
}

// MockQuestionUseCase is a mock of QuestionUseCase interface.
type MockQuestionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionUseCaseMockRecorder
	isgomock struct{}
}

// MockQuestionUseCaseMockRecorder is the mock recorder for MockQuestionUseCase.
type MockQuestionUseCaseMockRecorder struct {
	mock *MockQuestionUseCase
}

// NewMockQuestionUseCase creates a new mock instance.
func NewMockQuestionUseCase(ctrl *gomock.Controller) *MockQuestionUseCase {
	mock := &MockQuestionUseCase{ctrl: ctrl}
	mock.recorder = &MockQuestionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionUseCase) EXPECT() *MockQuestionUseCaseMockRecorder {
	return m.recorder
}

// CreateQuestion mocks base method.
func (m *MockQuestionUseCase) CreateQuestion(ctx context.Context, question *domain.Question) (*domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", ctx, question)
	ret0, _ := ret[0].(*domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockQuestionUseCaseMockRecorder) CreateQuestion(ctx, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockQuestionUseCase)(nil).CreateQuestion), ctx, question)
}

// DeleteQuestion mocks base method.
func (m *MockQuestionUseCase) DeleteQuestion(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockQuestionUseCaseMockRecorder) DeleteQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockQuestionUseCase)(nil).DeleteQuestion), ctx, id)
}

// GetAllQuestions mocks base method.
func (m *MockQuestionUseCase) GetAllQuestions(ctx context.Context) ([]domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuestions", ctx)
	ret0, _ := ret[0].([]domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuestions indicates an expected call of GetAllQuestions.
func (mr *MockQuestionUseCaseMockRecorder) GetAllQuestions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuestions", reflect.TypeOf((*MockQuestionUseCase)(nil).GetAllQuestions), ctx)
}

// GetQuestionByID mocks base method.
func (m *MockQuestionUseCase) GetQuestionByID(ctx context.Context, id primitive.ObjectID) (*domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionByID", ctx, id)
	ret0, _ := ret[0].(*domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionByID indicates an expected call of GetQuestionByID.
func (mr *MockQuestionUseCaseMockRecorder) GetQuestionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionByID", reflect.TypeOf((*MockQuestionUseCase)(nil).GetQuestionByID), ctx, id)
}

// GetQuestionsByExamID mocks base method.
func (m *MockQuestionUseCase) GetQuestionsByExamID(ctx context.Context, examID primitive.ObjectID) ([]domain.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsByExamID", ctx, examID)
	ret0, _ := ret[0].([]domain.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionsByExamID indicates an expected call of GetQuestionsByExamID.
func (mr *MockQuestionUseCaseMockRecorder) GetQuestionsByExamID(ctx, examID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsByExamID", reflect.TypeOf((*MockQuestionUseCase)(nil).GetQuestionsByExamID), ctx, examID)
}

// UpdateQuestion mocks base method.
func (m *MockQuestionUseCase) UpdateQuestion(ctx context.Context, question *domain.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockQuestionUseCaseMockRecorder) UpdateQuestion(ctx, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockQuestionUseCase)(nil).UpdateQuestion), ctx, question)
}

// MockExamUseCase is a mock of ExamUseCase interface.
type MockExamUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockExamUseCaseMockRecorder
	isgomock struct{}
}

// MockExamUseCaseMockRecorder is the mock recorder for MockExamUseCase.
type MockExamUseCaseMockRecorder struct {
	mock *MockExamUseCase
}

// NewMockExamUseCase creates a new mock instance.
func NewMockExamUseCase(ctrl *gomock.Controller) *MockExamUseCase {
	mock := &MockExamUseCase{ctrl: ctrl}
	mock.recorder = &MockExamUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExamUseCase) EXPECT() *MockExamUseCaseMockRecorder {
	return m.recorder
}

// CreateExam mocks base method.
func (m *MockExamUseCase) CreateExam(ctx context.Context, exam *domain.Exam) (*domain.Exam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExam", ctx, exam)
	ret0, _ := ret[0].(*domain.Exam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExam indicates an expected call of CreateExam.
func (mr *MockExamUseCaseMockRecorder) CreateExam(ctx, exam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExam", reflect.TypeOf((*MockExamUseCase)(nil).CreateExam), ctx, exam)
}

// DeleteExam mocks base method.
func (m *MockExamUseCase) DeleteExam(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExam", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExam indicates an expected call of DeleteExam.
func (mr *MockExamUseCaseMockRecorder) DeleteExam(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExam", reflect.TypeOf((*MockExamUseCase)(nil).DeleteExam), ctx, id)
}

// GenerateExamUsingAI mocks base method.
func (m *MockExamUseCase) GenerateExamUsingAI(ctx context.Context, userID primitive.ObjectID, numQuestions, numTasks int, topic, grade string) (*domain.ExamDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateExamUsingAI", ctx, userID, numQuestions, numTasks, topic, grade)
	ret0, _ := ret[0].(*domain.ExamDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateExamUsingAI indicates an expected call of GenerateExamUsingAI.
func (mr *MockExamUseCaseMockRecorder) GenerateExamUsingAI(ctx, userID, numQuestions, numTasks, topic, grade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateExamUsingAI", reflect.TypeOf((*MockExamUseCase)(nil).GenerateExamUsingAI), ctx, userID, numQuestions, numTasks, topic, grade)
}

// GetAllExams mocks base method.
func (m *MockExamUseCase) GetAllExams(ctx context.Context) ([]domain.Exam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllExams", ctx)
	ret0, _ := ret[0].([]domain.Exam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExams indicates an expected call of GetAllExams.
func (mr *MockExamUseCaseMockRecorder) GetAllExams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExams", reflect.TypeOf((*MockExamUseCase)(nil).GetAllExams), ctx)
}

// GetExamByID mocks base method.
func (m *MockExamUseCase) GetExamByID(ctx context.Context, id primitive.ObjectID) (*domain.Exam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExamByID", ctx, id)
	ret0, _ := ret[0].(*domain.Exam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExamByID indicates an expected call of GetExamByID.
func (mr *MockExamUseCaseMockRecorder) GetExamByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExamByID", reflect.TypeOf((*MockExamUseCase)(nil).GetExamByID), ctx, id)
}

// GetExamWithDetails mocks base method.
func (m *MockExamUseCase) GetExamWithDetails(ctx context.Context, id primitive.ObjectID) (*domain.ExamDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExamWithDetails", ctx, id)
	ret0, _ := ret[0].(*domain.ExamDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExamWithDetails indicates an expected call of GetExamWithDetails.
func (mr *MockExamUseCaseMockRecorder) GetExamWithDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExamWithDetails", reflect.TypeOf((*MockExamUseCase)(nil).GetExamWithDetails), ctx, id)
}

// GetExamsByUser mocks base method.
func (m *MockExamUseCase) GetExamsByUser(ctx context.Context, userID primitive.ObjectID) ([]domain.Exam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExamsByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Exam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExamsByUser indicates an expected call of GetExamsByUser.
func (mr *MockExamUseCaseMockRecorder) GetExamsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExamsByUser", reflect.TypeOf((*MockExamUseCase)(nil).GetExamsByUser), ctx, userID)
}

// UpdateExam mocks base method.
func (m *MockExamUseCase) UpdateExam(ctx context.Context, exam *domain.Exam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExam", ctx, exam)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExam indicates an expected call of UpdateExam.
func (mr *MockExamUseCaseMockRecorder) UpdateExam(ctx, exam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExam", reflect.TypeOf((*MockExamUseCase)(nil).UpdateExam), ctx, exam)
}

// UpdateExamStatus mocks base method.
func (m *MockExamUseCase) UpdateExamStatus(ctx context.Context, id primitive.ObjectID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExamStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExamStatus indicates an expected call of UpdateExamStatus.
func (mr *MockExamUseCaseMockRecorder) UpdateExamStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExamStatus", reflect.TypeOf((*MockExamUseCase)(nil).UpdateExamStatus), ctx, id, status)
}
